OneForAll/OneForAll/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='Home'),
    path('profiles/',include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

OneForAll/posts/urls.py
from django.urls import path
from .views import PostDeleteView,PostUpdateView, post_create_list_view, like_unlike_post, DeleteView

app_name = 'posts'

urlpatterns = [
    path('',post_create_list_view, name='main_post_view'),
    path('liked/',like_unlike_post, name='like_unlike_view'),
    path('<pk>/delete/',PostDeleteView.as_view(), name = 'post_delete'),
    path('<pk>/edit/',PostUpdateView.as_view(), name = 'post_edit'),
]

OneForAll/profiles/urls.py
from django.urls import path
from .views import ProfileDetailsView, accept_request, decline_request, profile_view, remove_connection, requests_received_view,request_profiles_list_view,ProfileListView,send_requests

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name = 'allprofiles'),
    path('myprofile/', profile_view, name = 'myprofile'),
    path('my_requests/', requests_received_view, name = 'myrequests'),
    path('<slug>/',ProfileDetailsView.as_view(), name = 'profile_details'),
    path('/to-invite/', request_profiles_list_view, name = 'invite_profiles'),
    path('/send_request/', send_requests, name = 'send_request'),
    path('/remove_connection/', remove_connection, name = 'remove_connection'),
    path('my_requests/accept_request/', accept_request, name = 'accept_request'),
    path('my_requests/decline_request/', decline_request, name = 'decline_request'),
]

OneForAll/OneForAll/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    user = request.user
    hello = 'Hello World'

    context = {
        'user' : user,
        'hello' : hello
    }
    return render(request,'main/home.html',context)
    #return HttpResponse('Hello World')

OneForAll/OneForAll/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
    home
{% endblock title %}

{% block content %}
    {{hello}}
    <br>
    {{user}}
{% endblock content %}

{% block scripts %}
<script>
$(document).ready(function(){
    console.log('working')
})
</script>
{% endblock scripts %}

OneForAll/OneForAll/templates/main/navbar.html
{% url 'posts:main_post_view' as posts_path %}
{% url 'Home' as home_path %}
{% url 'profiles:myprofile' as myprofile_path %}
{% url 'profiles:myrequests' as myrequests_path %}
{% url 'profiles:invite_profiles' as send_request_path %}
{% url 'profiles:allprofiles' as profiles_path %}


<div class="ui inverted menu nav mb-7">
    <div class="ui container">
      <a href="{{home_path}}" class="{% if request.path == home_path %} active {% endif %}item">
          <h3>OneForAll</h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="{{posts_path}}" class="{% if request.path == posts_path %} active {% endif %} item">
          Posts
      </a>
      {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button purple"> Followers
                  <i class="dropdown icon"></i>
                  <div class="menu">
                      <a href="{{profiles_path}}" class="{% if request.path == profiles_path %} active {% endif %}item">
                          All Profiles
                      </a>
                      <a href="{{send_request_path}}" class="{% if request.path == send_request_path %} active {% endif %}item">
                          Send Requests
                      </a>
                      <a href="{{myrequests_path}}" class="{% if request.path == myrequests_path %} active {% endif %}item">
                          Requests Received &nbsp; <div class="ui purple horizontal label">{{request_no}}</div>
                      </a>
                  </div>
               </div>
          </div>
               <div class="item">
                <form action="" method="GET">
                  <div class="ui action left icon input">
                  <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div>
          
              <a href="{{myprofile_path}}" class="{% if request.path == myprofile_path %} active {% endif %}item">
                  <img src="{{picture.url}}" class="ui avatar image">&nbsp;
                   {{ request.user }}
              </a>
  
              <a href="{% url 'account_logout' %}" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="{% url 'account_login' %}" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
</div>