OneForAll/OneForAll/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='Home'),
    path('profiles/',include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

OneForAll/posts/urls.py
from django.urls import path
from .views import PostDeleteView,PostUpdateView, post_create_list_view, like_unlike_post, DeleteView

app_name = 'posts'

urlpatterns = [
    path('',post_create_list_view, name='main_post_view'),
    path('liked/',like_unlike_post, name='like_unlike_view'),
    path('<pk>/delete/',PostDeleteView.as_view(), name = 'post_delete'),
    path('<pk>/edit/',PostUpdateView.as_view(), name = 'post_edit'),
]

OneForAll/profiles/urls.py
from django.urls import path
from .views import ProfileDetailsView, accept_request, decline_request, profile_view, remove_connection, requests_received_view,request_profiles_list_view,ProfileListView,send_requests

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name = 'allprofiles'),
    path('myprofile/', profile_view, name = 'myprofile'),
    path('my_requests/', requests_received_view, name = 'myrequests'),
    path('<slug>/',ProfileDetailsView.as_view(), name = 'profile_details'),
    path('/to-invite/', request_profiles_list_view, name = 'invite_profiles'),
    path('/send_request/', send_requests, name = 'send_request'),
    path('/remove_connection/', remove_connection, name = 'remove_connection'),
    path('my_requests/accept_request/', accept_request, name = 'accept_request'),
    path('my_requests/decline_request/', decline_request, name = 'decline_request'),
]

OneForAll/profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.db.models import aggregates
from django.db.models.deletion import CASCADE
from django.db.models.fields import SlugField
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from .utils import get_randomcode
from django.db.models import Q
from django.template.defaultfilters import slugify
# Create your models here.
CATEGORY_CHOICES = (
    ('Startup Member','Startup Member'),
    ('Investor','Investor')
)

FIELDS = (
    ('Technology','Technology'),
    ('Textiles','Textiles'),
    ('Sculptures and Paintings','Sculptures and Paintings'),
    ('Sports','Sports'),
    ('Music','Music'),
    ('Food and Health','Food and Health')
)

class ProfileManager(models.Manager):

    def get_profiles_to_request(self, sender):
        profiles = Profiles.objects.all().exclude(user = sender)
        profile = Profiles.objects.get(user = sender)
        qs = Relationship.objects.filter(Q(sender=profile)| Q(receiver=profile))
        print(qs)

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        return available

    def get_all_profiles(self, me):
        profile = Profiles.objects.all().exclude(user=me)
        return profile

class Profiles(models.Model):
    first_name = models.CharField(max_length=200, blank = True)
    last_name = models.CharField(max_length=200, blank = True)
    user = models.OneToOneField(User, on_delete=CASCADE)
    about = models.TextField(default = "no bio", max_length=300)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='Startup Member')
    field_of_interest = models.CharField(max_length = 50, choices=FIELDS, default='NONE')
    email = models.EmailField(max_length=200,blank = True)
    country = models.CharField(max_length=200,blank = True)
    profile_pic = models.ImageField(default = 'avatar.png',upload_to = 'profile_pic/')
    followers = models.ManyToManyField(User, blank = True,related_name = 'followers')
    slug = models.SlugField(unique=True,blank = True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"
    
    def get_absolute_url(self):
        return reverse("profiles:profile_details", kwargs = {"slug":self.slug})
    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def get_followers(self):
        return self.followers.all()
    
    def get_follow_count(self):
        return self.followers.all().count()

    def get_no_of_posts(self):
        return self.posts.all().count()
    
    def get_posts(self):
        return self.posts.all()
    
    def likes_given(self):
        likes = self.like_set.all()
        total_likes = 0
        for i in likes:
            if i.value == 'Like':
                total_likes+=1
        return total_likes

    def likes_received(self):
        posts = self.posts.all()
        total_likes = 0
        for post in posts:
            total_likes += post.liked.all().count()
        return total_likes
    
    def save(self, *args,**kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == "":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name)+" "+str(self.last_name))
                ex = Profiles.objects.filter(slug = to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_randomcode))
                    ex = Profiles.objects.filter(slug = to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args,**kwargs)

STATUS_CHOICES = (
    ('sent','sent'),
    ('accepted','accepted')
)

class RelationshipManager(models.Manager):
    def requests_received(self, receiver):
        queryset = Relationship.objects.filter(receiver=receiver, status = 'sent')
        return queryset



class Relationship(models.Model):
    sender = models.ForeignKey(Profiles, on_delete = CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profiles, on_delete = CASCADE, related_name='receiver')
    status = models.CharField(max_length=10, choices = STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

OneForAll/profiles/forms.py
from django import forms
from .models import Profiles

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profiles
        fields = ('first_name','last_name','email','about','category','field_of_interest','profile_pic')

OneForAll/profiles/views.py
from django.contrib.auth import login
from django.shortcuts import render, resolve_url,redirect,get_object_or_404
from django.utils import tree
from .models import Profiles, Relationship
from .forms import ProfileForm
from django.views.generic import ListView,DetailView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

@login_required
def profile_view(request):
    obj = Profiles.objects.get(user = request.user)
    form = ProfileForm(request.POST or None, request.FILES or None, instance=obj)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': obj,
        'form' : form,
        'confirm' : confirm
    }

    return render(request, 'profiles/myprofile.html', context)

class ProfileDetailsView(LoginRequiredMixin ,DetailView):
    model = Profiles
    template_name = 'profiles/profile_detail.html'

    # def get_object(self, slug=None):
    #     slug = self.kwargs.get('slug')
    #     #id = self.kwargs.get('id')
    #     profile = Profiles.objects.get(slug=slug)
    #     return profile

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profiles.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver = profile)
        rel_receiver = []
        rel_sender = []
        for rel in rel_r:
            rel_receiver.append(rel.receiver.user)
        for rel in rel_s:
            rel_sender.append(rel.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_posts()
        context['no_posts'] = True if len(self.get_object().get_posts()) > 0 else False 

        return context

@login_required
def requests_received_view(request):
    profile = Profiles.objects.get(user = request.user)
    queryset = Relationship.objects.requests_received(profile)

    result = list(map(lambda x:x.sender, queryset))
    is_empty = False
    if len(result) == 0:
        is_empty = True

    context = {'qs':result,
                'is_empty':is_empty}

    return render(request, 'profiles/my_requests.html', context)

@login_required
def request_profiles_list_view(request):
    user = request.user
    qs = Profiles.objects.get_profiles_to_request(user)

    context = {'qs':qs}

    return render(request, 'profiles/to_invite_list.html', context)

@login_required
def profiles_list_view(request):
    user = request.user
    qs = Profiles.objects.get_all_profiles(user)

    context = {'qs':qs}

    return render(request, 'profiles/profile_list.html', context)

class ProfileListView(LoginRequiredMixin ,ListView):
    model = Profiles
    template_name = 'profiles/profile_list.html'
    context_object_name = 'qs'

    def get_queryset(self):
        qs = Profiles.objects.get_all_profiles(self.request.user)
        return qs
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profiles.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver = profile)
        rel_receiver = []
        rel_sender = []
        for rel in rel_r:
            rel_receiver.append(rel.receiver.user)
        for rel in rel_s:
            rel_sender.append(rel.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context

@login_required
def send_requests(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profiles.objects.get(user = user)
        receiver = Profiles.objects.get(pk = pk)
        rel = Relationship.objects.create(sender = sender, receiver = receiver, status = 'sent')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:myprofile')

@login_required
def remove_connection(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profiles.objects.get(user = user)
        receiver = Profiles.objects.get(pk = pk)

        rel = Relationship.objects.get(
            (Q(sender = sender) & Q(receiver = receiver))|
            (Q(sender=receiver) & Q(receiver = sender)))
        rel.delete()

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:myprofile')

@login_required
def accept_request(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profiles.objects.get(pk=pk)
        receiver = Profiles.objects.get(user = request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'sent':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:myrequests')

@login_required
def decline_request(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profiles.objects.get(pk=pk)
        receiver = Profiles.objects.get(user = request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:myrequests')

OneForAll/profiles/templates/profiles/my_requests.html
{% extends 'base.html' %}

{% block title %}
    My Requests
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h2>No Connection Requests Yet</h2>
    {% endif %}
        {% for obj in qs %}
        <div class="ui segment">
            <div class = "ui grid">
                <div class="ui three wide column">
                    <img class="ui small circular image" src="{{obj.profile_pic.url}}">
                </div>
                <div class="thirteen wide column">
                    <a href = ""><h3>{{obj.user}}</h3></a>
                    <div class="content">
                        <div class="description">
                        {{obj.about}}
                        </div>
                    </div>
                    <form action="{% url 'profiles:accept_request' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value = {{obj.pk}}>
                        <button type="submit" class="ui positive basic button">
                            Accept Request
                        </button>
                    </form>
                    <form action="{% url 'profiles:decline_request' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value = {{obj.pk}}>
                        <button type="submit" class="ui negative basic button">
                            Decline Request
                        </button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock content %}

OneForAll/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}

{% block title %}
My Profile
{% endblock title %}

{% block content %}
<!--MODAL-->
<div class="ui modal custommod">
    <i class="close icon"></i>
    <div class="header">
      Update Profile
    </div>
    <div class="image content">
      <div class="ui medium image">
        <img src="{{profile.profile_pic.url}}">
      </div>
      <div class="description">
        <div class="ui header">Update Your Profile Details</div>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <!--<button type="submit" class="ui purple button">Update Profile</button>-->
        
      </div>
    </div>
    <div class="actions">
      <!--<button type="submit" class="ui positive right labeled icon button">
        Done
        <i class="checkmark icon"></i>
      </button>-->
     <button type="submit" class="ui animated fade button ui purple button">
        <div class="visible content">Done</div>
        <div class="hidden content">
            <i class="checkmark icon"></i>
        </div>
    </button>
    </form>
  </div>
</div>


<div class = "ui segment">
    {% if confirm %}
        <div class="ui green message">Profile Updated!</div>
    {% endif %}
    <h3>{{request.user}}'s Profile</h3>
    <div class="ui grid">
    <div class="row">
        <div class = 'six wide column'>
            <img class = "ui small circular image" src = {{profile.profile_pic.url}}>
            <div class="row mt-5">
                <button class="ui violet button" id = 'modal-button'>Update Profile</button>
            </div>
            <!--<button class="ui ">Connections:</h3>
            <h4>{{profile.get_follow_count}}</h4>-->
        </div>
        <div class = "ten wide column">
          <table class="ui table">
            <tbody>
              <tr>
                <td>Username :</td>
                <td>{{profile.user}}</td>
              </tr>
              <tr>
                <td>Name :</td>
                <td>{{profile.first_name}} {{profile.last_name}}</td>
              </tr>
              <tr>
                <td>email :</td>
                <td>{{profile.email}}</td>
              </tr>
              <tr>
                <td>About :</td>
                <td>{{profile.about}}</td>
              </tr>
              <tr>
                <td>Field Of Interest :</td>
                <td>{{profile.field_of_interest}}</td>
              </tr>
              <tr>
                <td>Category :</td>
                <td>{{profile.category}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <button class="ui violet button" id = 'profile-modal'>Connections : {{profile.get_follow_count}}</button>
  </div>
<div class="twelve wide column">
    <h2>Posts Uploaded</h2>
    {% if count %}
        {% for post in posts %}
            <div class="ui segment fluid">
                {{post.caption}}
            </div>
        {% endfor %}
    {% else %}
        <h1>No Posts Uploaded by you yet.</h1>
    {% endif %}
</div>
{% endblock content %}

OneForAll/profiles/templates/profiles/profile_detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.user}}
{% endblock title %}

{% block content %}
    <div class = "ui grid">
        <div class="row">
            <div class="four wide column">
                <img class="image medium rounded image" src="{{object.profile_pic.url}}">
                <h1>{{object.user}}</h1>
                <div class="ui vertical menu">
                    <div class="item">
                        POSTS
                        <div class="ui violet label"><i class="heart icon"></i>{{object.get_no_of_posts}}</div>
                    </div>
                    <div class="item">
                        Followers
                        <div class="ui violet label"><i class="user icon"></i>{{object.get_follow_count}}</div>
                    </div>
                </div>
                {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'profiles:send_request' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name='profile_pk' value = {{object.pk}}>
                        <button type="submit" class = 'ui animated fade violet mini button'>
                            <div class="visible content">Add Connection</div>
                                <div class="hidden content">
                                    <i class="user plus icon"></i>
                                </div>
                        </button>
                </form>
                {% endif %}

                {% if object.user in rel_receiver and request.user not in object.followers.all %}
                    <button type="submit" class = 'ui disabled grey mini button'>
                        Request Sent
                    </button>
                {% endif %}


                {% if request.user in object.followers.all %}
                <form action="{% url 'profiles:remove_connection' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name='profile_pk' value = {{object.pk}}>
                        <button type="submit" class = 'ui animated fade red mini button'>
                            <div class="visible content">Remove Connection</div>
                                <div class="hidden content">
                                    <i class="user times icon"></i>
                                </div>
                        </button>
                </form>
                {% endif %}
            </div>
            <div class="twelve wide column">
                {% if no_posts %}
                    {% for post in posts %}
                        <div class="ui segment fluid">
                            {{post.caption}}
                        </div>
                    {% endfor %}
                {% else %}
                    <h1>No Posts Uploaded by {{object.user}} yet.</h1>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

OneForAll/profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
    Profiles
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No Profiles Found</h1>
    {% endif %}
    {% for obj in object_list %}
        <div class="ui divided massive list">
            <div class="item">
            <img class="ui avatar image" src="{{obj.profile_pic.url}}">
            <div class="content">
                <h3><a href = "{{obj.get_absolute_url}}" class="header">{{obj.user}} - ({{obj.category}})</a></h3>
                <div class="description"><h5>{{obj.about}}</h5></div>
                <!-- <form action="" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name='profile_pk' value = {{obj.pk}}>

                </form> -->

                {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                <form action="{% url 'profiles:send_request' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name='profile_pk' value = {{obj.pk}}>
                        <button type="submit" class = 'ui animated fade violet mini button'>
                            <div class="visible content">Add Connection</div>
                                <div class="hidden content">
                                    <i class="user plus icon"></i>
                                </div>
                        </button>
                </form>
                {% endif %}

                {% if obj.user in rel_receiver and request.user not in obj.followers.all %}
                    <button type="submit" class = 'ui disabled grey mini button'>
                        Request Sent
                    </button>
                {% endif %}


                {% if request.user in obj.followers.all %}
                <form action="{% url 'profiles:remove_connection' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name='profile_pk' value = {{obj.pk}}>
                        <button type="submit" class = 'ui animated fade red mini button'>
                            <div class="visible content">Remove Connection</div>
                                <div class="hidden content">
                                    <i class="user times icon"></i>
                                </div>
                        </button>
                </form>
                {% endif %}

            </div>
            </div>
        </div>
    {% endfor %}
    <!--<ul>
        {% for item in qs %}
            <li>{{item}}</li>
        {% endfor %}
    </ul>-->
{% endblock content %}

OneForAll/profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
    Request List
{% endblock title %}

{% block content %}
    <ul>
        {% for item in qs %}
            <li>{{item}}</li>
        {% endfor %}
    </ul>
{% endblock content %}