OneForAll/OneForAll/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='Home'),
    path('profiles/',include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

OneForAll/posts/urls.py
from django.urls import path
from .views import PostDeleteView,PostUpdateView, post_create_list_view, like_unlike_post, DeleteView

app_name = 'posts'

urlpatterns = [
    path('',post_create_list_view, name='main_post_view'),
    path('liked/',like_unlike_post, name='like_unlike_view'),
    path('<pk>/delete/',PostDeleteView.as_view(), name = 'post_delete'),
    path('<pk>/edit/',PostUpdateView.as_view(), name = 'post_edit'),
]

OneForAll/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.db.models.query_utils import FilteredRelation
from profiles.models import Profiles


class Post(models.Model):
    caption = models.TextField()
    image = models.ImageField(upload_to = 'posts', validators = [FileExtensionValidator(['png','jpg','jpeg'])], blank = True)
    liked = models.ManyToManyField(Profiles, blank = True, related_name='likes')
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profiles, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(self.caption[:20])
    
    def likes_num(self):
        return self.liked.all().count()

    def comments_num(self):
        return self.comment_set.all().count()
        

    class Meta:
        ordering = ('-created',)

class Comment(models.Model):
    user = models.ForeignKey(Profiles, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        #return str(self.pk)
        return f"{self.pk}-{self.post.pk}-{self.user}"


LIKEORNO = (
    ('Like','Like'),
    ('Unlike','Unlike'),
)
class Like(models.Model):
    user = models.ForeignKey(Profiles, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKEORNO, max_length=8)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

OneForAll/posts/forms.py
from django import forms
from django.db.models import fields
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('caption','image')

class CommentModelForm(forms.ModelForm):
    text = forms.CharField(label = '', widget=forms.TextInput(attrs={'placeholder':'Comment'}))
    class Meta:
        model = Comment
        fields = ('text',)

OneForAll/posts/views.py
from django.core.checks import messages
from django.http import request
from profiles.models import Profiles
from django.shortcuts import render, redirect
from .models import Post,Like
from django.urls import reverse_lazy
from .forms import PostModelForm, CommentModelForm
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

@login_required
def post_create_list_view(request):
    queryset = Post.objects.all()
    profile = Profiles.objects.get(user=request.user)

    p_form = PostModelForm()
    c_form = CommentModelForm()
    posted = False

    profile = Profiles.objects.get(user=request.user)

    if 'submit_post' in request.POST:
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            posted = True

    if 'submit_comment' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            post_id = request.POST.get('post_id')
            instance.post = Post.objects.get(id=post_id)
            instance.save()
            c_form = CommentModelForm()

    context = {
        'queryset':queryset,
        'profile' : profile,
        'p_form' : p_form,
        'c_form' : c_form,
        'posted' : posted,
    }

    return render(request, 'posts/main.html', context)

@login_required
def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profiles.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id = post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        else:
            like.value='Like'

        post_obj.save()
        like.save()

        data = {
            'value':like.value,
            'likes':post_obj.liked.all().count()
        }
    
    return redirect('posts:main_post_view')

class PostDeleteView(LoginRequiredMixin ,DeleteView):
    model = Post
    template_name = 'posts/are_you_sure.html'
    success_url = reverse_lazy('posts:main_post_view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk = pk)
        if not obj.author.user==self.request.user:
            messages.warning(self.request, "You do not have the permission to delete this post since you have not uploaded it")
        return obj

class PostUpdateView(LoginRequiredMixin ,UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/edit_post.html'
    success_url = reverse_lazy('posts:main_post_view')

    def form_valid(self, form):
        profile = Profiles.objects.get(user = self.request.user)

        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You do not have the permission to edit this post since you have not uploaded it")
            return super().form_invalid(form)

OneForAll/posts/templates/posts/are_you_sure.html
{% extends 'base.html' %}

{% block title %}
    Delete Post
{% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class="ui native message">
                    <div class="header">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if not messages %}
        <div class="ui segment">
            <h3>Deleting Post....</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you Sure you want to delete this post?</p>
                <button type="submit" class="ui primary button">Yes</button>
            </form>
        </div>
    {% endif %}
{% endblock content %}

OneForAll/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit Post
{% endblock title %}

{% block content %}
    <div class="ui segment">
        <h3>Edit Post</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button type="submit" class="ui button primary">Update</button>
        </form>
    </div>
{% endblock content %}

OneForAll/posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in queryset %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% ifequal request.user obj.author.user %}
                            <a href="{% url 'posts:post_edit' obj.pk %}"><button class="ui button bwhite-lg ">Edit</button></a>
                            <a href="{% url 'posts:post_delete' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>
                    
                </div>
                <img class="ui avatar image" src={{obj.author.profile_pic.url}}> 
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.caption }} </p>
                <div class="right floated">
                    <form action="{% url 'posts:like_unlike_view' %}" method="POST" class="like-form" id="{{obj.id}}">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        <button type="submit" class="ui animated fade button violet like-btn{{obj.id}}">
                            {% if profile not in obj.liked.all %}
                                <div class="visible content txt{{obj.id}}">Like</div>
                                <div class="hidden content">
                                    <i class="thumbs up outline icon icon{{obj.id}}"></i>
                                </div>
                                <!--<span> {{obj.num_likes}} likes</span>-->
                            {% else %}
                                <div class="visible content txt{{obj.id}}">Unlike</div>
                                <div class="hidden content">
                                    <i class="thumbs down outline icon icon{{obj.id}}"></i>
                                </div>
                            {% endif %}
                        </button>
                        <!--<span> {{obj.num_likes}} likes</span>-->
                    </form>
                    <span class="right floated like-number{{obj.id}}">
                        <i class="heart outline like icon" id="likes"></i>
                        {{obj.likes_num}}
                    </span>
                    <i class="comments outline icon" id="comment"></i>
                    {{obj.comments_num}}
                </div>
                <!--<i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>-->
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.profile_pic.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.text }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method="POST" class="ui form">
                    {% csrf_token %}
                    {{c_form}}
                    <input type="hidden" name='post_id' value="{{obj.id}}">
                    <button type="submit" class="ui animated button violet" name='submit_comment'>
                        <div class="visible content">Comment</div>
                        <div class="hidden content">
                            <i class="comment icon"></i>
                        </div>
                    </button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if posted %}
            <div class="ui success message">
                <i class="close icon"></i>
                <div class="header">
                  Post Uploaded Sucessfuly
                </div>
            </div>
            {% endif %}
            <form action="" method="POST" class = "ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{p_form}}
                <button type="submit" class="ui animated button violet" name="submit_post">
                    <div class="visible content">Post</div>
                    <div class="hidden content">
                      <i class="paper plane outline icon"></i>
                    </div>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });

            $('.like-form').submit(function(e){
                e.preventDefault()
                const post_id = $(this).attr('id')
                
                const btn_text = $(`.like-btn${post_id}`).text()
                const trim = $.trim(btn_text)

                const url = $(this).attr('action')

                let res;
                const likes = $(`.like-number${post_id}`).text()
                const like_count = parseInt(likes)

                $.ajax({
                    type: 'POST',
                    url: url,
                    data :{
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },
                    success: function(response){
                        if(trim==='Unlike'){
                            $(`.like-btn${post_id}`).text('Like')
                            res = like_count - 1
                        }
                        else{
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = like_count + 1
                        }
                        $(`.like-number${post_id}`).text(res)
                    },
                    error: function(resposne){
                        console.log('error', response)
                    }
                })
            })
        });
    </script>
{% endblock scripts %}